- name: install mongodb
  apt: name={{ item }} state=present
  with_items:
    - mongodb

- name: trust all address on MongoDB
  replace: >
    dest=/etc/mongodb.conf
    regexp="^bind_ip =.*"
    replace="bind_ip = 0.0.0.0"

- name: start mongodb
  service: name=mongodb state=restarted
