#
# dependencies: [anyenv]
# setting_vars: [home_dir, shell]
#
- name: install ndenv
  shell: /bin/bash -lc "anyenv install -s ndenv"

- name: install ndenv-plugins
  git: repo="https://github.com/{{ item.name }}" dest="{{ home_dir }}/.anyenv/envs/ndenv/plugins/{{ item.path }}"
  with_items:
    - { name: 'kaave/ndenv-default-npms.git', path: 'ndenv-default-npms' }

- name: link default file ndenv-plugins
  file:
    src: "{{ home_dir }}/dotfiles/default_libraries/default-npms"
    dest: "{{ home_dir }}/.anyenv/envs/ndenv/default-npms"
    state: link

#
# dependencies: [libraries, ndenv]
# setting_vars: [home_dir, node_version, shell]
#
- name: install node with ndenv
  shell: /bin/bash -lc "ndenv install {{ node_version }}"

- name: set node version global
  shell: /bin/bash -lc "ndenv global {{ node_version }}"

- name: set node version global
  shell: /bin/bash -lc "ndenv rehash"

