# PostgreSQL
- name: install postgresql latest apt-repository
  shell: sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
  args:
    executable: /bin/{{ shell }}

- name: install key
  shell: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
  args:
    executable: /bin/{{ shell }}

- name: ensure apt cache is up to date
  apt: update_cache=yes

- name: ensure packages are installed
  apt: name={{ item }} state=latest
  with_items:
    - python-psycopg2
    - postgresql
    - postgresql-contrib

- name: ensure postgresql listen address
  replace: >
    dest=/etc/postgresql/{{ pg_version }}/main/postgresql.conf
    regexp="^#listen_addresses = 'localhost'"
    replace="listen_addresses = '*'"

- name: default locale and timezone
  replace: >
    dest=/etc/postgresql/{{ pg_version }}/main/postgresql.conf
    regexp="en_US.UTF-8"
    replace="ja_JP.UTF-8"

- name: local peer off on PostgreSQL - all
  replace: >
    dest=/etc/postgresql/{{ pg_version }}/main/pg_hba.conf
    regexp="local +all +all +peer"
    replace="local all all trust"

- name: local peer off on PostgreSQL - postgres
  replace: >
    dest=/etc/postgresql/{{ pg_version }}/main/pg_hba.conf
    regexp="local +all +postgres +peer"
    replace="local all postgres trust"

- name: trust all address on PostgreSQL
  lineinfile: dest=/etc/postgresql/{{ pg_version }}/main/pg_hba.conf line="host all all 0.0.0.0/0 trust"

- name: restart postgresql
  service: name=postgresql state=restarted

- name: ensure database is created
  postgresql_db: name={{ db_name }}

- name: ensure user has access to database
  postgresql_user: db={{ db_name }} name={{ dbuser_name }} password={{ dbuser_pass }} role_attr_flags=CREATEDB,LOGIN,REPLICATION
