- name: install redis
  apt: name=redis-server state=present

- name: trust all address on redis
  replace: >
    dest=/etc/redis/redis.conf
    regexp="^bind 127.0.0.1"
    replace="bind 0.0.0.0"

- name: start redis-server
  service: name=redis-server state=restarted
